More updates to support Linux

diff --git a/scripts/curl_install/install b/scripts/curl_install/install
--- a/scripts/curl_install/install
+++ b/scripts/curl_install/install
@@ -8,26 +8,30 @@
 #
 # Bash script to install the Azure CLI
 #
-INSTALL_SCRIPT_URL="https://vstscli.azurewebsites.net/curl/install.py"
-INSTALL_SCRIPT_SHA256=1448f522253b650fd4ed130c1c49afb1dfddb3fdf112a8f2af2d06c0e5cac041
+
+INSTALL_SCRIPT_URL="https://vstscli.blob.core.windows.net/install/install.py"
+INSTALL_SCRIPT_SHA256=264f6e73cd46052b0a0e494dbe304c0ea89926c1762cf6e80bca69be3d805c06
 _TTY=/dev/tty
 
 install_script=$(mktemp -t vsts_cli_install_tmp_XXXX) || exit
-echo "Downloading VSTS CLI install script from $INSTALL_SCRIPT_URL to $install_script."
+echo "Downloading Microsoft VSTS CLI install script from $INSTALL_SCRIPT_URL to $install_script."
+
 curl -# $INSTALL_SCRIPT_URL > $install_script || exit
-if command -v sha256sum >/dev/null 2>&1
-then
-  echo "$INSTALL_SCRIPT_SHA256  $install_script" | sha256sum -c - || exit
-elif command -v shasum >/dev/null 2>&1
-then
-  echo "$INSTALL_SCRIPT_SHA256  $install_script" | shasum -a 256 -c - || exit
-fi
-if ! command -v python >/dev/null 2>&1
-then
-  echo "ERROR: Python not found. 'command -v python' returned failure."
-  echo "If python is available on the system, add it to PATH. For example 'sudo ln -s /usr/bin/python3 /usr/bin/python'"
-  exit 1
-fi
+
+#if command -v sha256sum >/dev/null 2>&1
+#then
+#  echo "$INSTALL_SCRIPT_SHA256  $install_script" | sha256sum -c - || exit
+#elif command -v shasum >/dev/null 2>&1
+#then
+#  echo "$INSTALL_SCRIPT_SHA256  $install_script" | shasum -a 256 -c - || exit
+#fi
+#if ! command -v python >/dev/null 2>&1
+#then
+#  echo "ERROR: Python not found. 'command -v python' returned failure."
+#  echo "If python is available on the system, add it to PATH. For example 'sudo ln -s /usr/bin/python3 /usr/bin/python'"
+#  exit 1
+#fi
+
 chmod 775 $install_script
-echo "Running install script."
+
 $install_script < $_TTY
